#!/bin/bash -x
myname="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
mydirname=$(dirname ${myname})

# Check if an argument is provided
[ $# -lt 2 ] && echo "Usage: $0 old_tutorial_directory new_tutorial_directory" >&2 && exit 1

[ ! -d $1 ] && echo "Error: directory $1 must exist" >&2 && exit 1

[ -e $2 ] && echo "Error: $2 must NOT already exist" >&2 && exit 1

echo [ -z $(dirname $2) ] && [ ! -d $(dirname $2) ] && mkdir -p $(dirname $2)

cp -r $1 $2

pushd $2
rm -rf .chromium-browser __pycache__ requirements.txt runme.py setmeup.py .venv
wget -O main.py https://github.com/fastapi/fastapi/raw/refs/heads/master/docs_src/$2
sed -i -e "s#$1#$2#g" README.md

popd
sed -i -e "s#$1#$2#g" RUNME

