#!/bin/bash
if ! (which python3 >/dev/null && python3 --version | grep ' 3.' >/dev/null); then
  echo "You must have python 3 installed to run this."
  exit 1
fi

cd $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

[ -x $(which kate) ] && kate --new ../RUNME ./RUNME query_params_str_validations/tutorial003_an_py310.py/RUNME &

python3 $(dirname "$(readlink -f "$0")")/runme.py "https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#additional-validation" "https://github.com/fastapi/fastapi/blob/master/docs_src/query_params_str_validations/tutorial003_an_py310.py" "https://github.com/pflagerd/fastapi_learn_tutorial_user_guide/tree/master/query_params_str_validations/tutorial003_an_py310.py"



