#!/bin/bash

# Check if an argument is provided
[ $# -lt 2 ] && echo "Usage: $0 old_tutorial_directory new_tutorial_directory" >&2 && exit 1

[ ! -d $1 ] && echo "Error: directory $1 must exist" >&2 && exit 1

[ -e $2 ] && echo "Error: $2 must NOT already exist" >&2 && exit 1

cp -r $1 $2
cd $2
rm -rf .chromium-browser __pycache__ requirements.txt runme.py setmeup.py .venv
wget -O main.py https://github.com/fastapi/fastapi/raw/refs/heads/master/docs_src/path_params/$2
sed -i -e "s#$1#$2#g" README.md

sed -i -e "s#$1#$2#g" ../RUNME

sed -i -e "s#$1#$2#g" ../../david-and-dan/launch-konsole-with-tabs.bash

